//! Chronos theme bridge.
//!
//! Consumers import this module as `use chronos_fm_ui::theme::theme;` and call
//! e.g. `theme::bg(cx)`. Every function resolves the *live* gpui-component
//! theme (`cx.theme()`, which derefs to `ThemeColor`) so the whole UI follows
//! the active Chronos Dark / Chronos Light palette and the runtime
//! light/dark/system toggle wired up in `crates/chronos-fm/src/app.rs`.
//!
//! The palette itself lives in
//! `crates/chronos-fm/assets/themes/chronos.theme.json` (generated by
//! `script/dev/gen_chronos_theme.py` from the design spec seed). Tokens that
//! have no direct `ThemeColor` analogue — the `TOOLBAR_*` set — are mapped to
//! the nearest semantic field, documented inline below.

use gpui::{App, Hsla, hsla};
use gpui_component::ActiveTheme;

/// Inner module kept under the historical public path so `theme::theme` still
/// resolves in every consumer (`use chronos_fm_ui::theme::theme;`).
#[allow(clippy::module_inception)]
pub mod theme {
    use super::*;

    /// Pure white.
    pub fn white(_cx: &App) -> Hsla {
        hsla(0.0, 0.0, 1.0, 1.0)
    }
    /// Pure black.
    pub fn black(_cx: &App) -> Hsla {
        hsla(0.0, 0.0, 0.0, 1.0)
    }

    // --- Grayscale steps: mapped to the nearest semantic theme field --------
    /// Lightest surface (e.g. zebra rows) → `list_even`.
    pub fn gray_50(cx: &App) -> Hsla {
        cx.theme().list_even
    }
    /// Light surface → `secondary`.
    pub fn gray_100(cx: &App) -> Hsla {
        cx.theme().secondary
    }
    /// Default border → `border`.
    pub fn gray_200(cx: &App) -> Hsla {
        cx.theme().border
    }
    /// Border-on-hover → `border` (no dedicated field; neutral).
    pub fn gray_300(cx: &App) -> Hsla {
        cx.theme().border
    }
    /// Muted text → `muted_foreground`.
    pub fn gray_400(cx: &App) -> Hsla {
        cx.theme().muted_foreground
    }
    /// Secondary text → `secondary_foreground`.
    pub fn gray_500(cx: &App) -> Hsla {
        cx.theme().secondary_foreground
    }
    /// Secondary text (dark gray in light theme) → `secondary_foreground`.
    pub fn gray_600(cx: &App) -> Hsla {
        cx.theme().secondary_foreground
    }
    /// High-emphasis text → `foreground`.
    pub fn gray_700(cx: &App) -> Hsla {
        cx.theme().foreground
    }
    /// Darker surface → `secondary`.
    pub fn gray_800(cx: &App) -> Hsla {
        cx.theme().secondary
    }
    /// Darkest surface (toolbar) → `sidebar`.
    pub fn gray_900(cx: &App) -> Hsla {
        cx.theme().sidebar
    }

    // --- Main background and text -------------------------------------------
    /// Primary surface background → `background` (seed bg.primary).
    pub fn bg(cx: &App) -> Hsla {
        cx.theme().background
    }
    /// Secondary surface background → `secondary` (seed bg.secondary).
    pub fn bg_secondary(cx: &App) -> Hsla {
        cx.theme().secondary
    }
    /// Hovered surface background → neutral `list_hover`.
    pub fn bg_hover(cx: &App) -> Hsla {
        cx.theme().list_hover
    }
    /// Primary foreground (text) → `foreground` (seed text.primary).
    pub fn fg(cx: &App) -> Hsla {
        cx.theme().foreground
    }
    /// Secondary foreground (text) → `secondary_foreground`.
    pub fn fg_secondary(cx: &App) -> Hsla {
        cx.theme().secondary_foreground
    }
    /// Muted foreground → `muted_foreground`.
    pub fn muted(cx: &App) -> Hsla {
        cx.theme().muted_foreground
    }

    // --- UI elements --------------------------------------------------------
    /// Default border → `border`.
    pub fn border(cx: &App) -> Hsla {
        cx.theme().border
    }
    /// Border on hover → `muted_foreground` (mid gray).
    pub fn border_hover(cx: &App) -> Hsla {
        cx.theme().muted_foreground
    }

    // --- Toolbar (left nav rail). No direct ThemeColor analogue → nearest -----
    /// Toolbar background → `sidebar` (subtle nav-rail surface, distinct from page bg).
    pub fn toolbar_bg(cx: &App) -> Hsla {
        cx.theme().sidebar
    }
    /// Toolbar item hover → `sidebar_accent` (subtle accent tint).
    pub fn toolbar_hover(cx: &App) -> Hsla {
        cx.theme().sidebar_accent
    }
    /// Toolbar text → `sidebar_foreground` (= `foreground`).
    pub fn toolbar_text(cx: &App) -> Hsla {
        cx.theme().sidebar_foreground
    }
    /// Active toolbar item bg → `list_active` (selected/active subtle accent tint).
    pub fn toolbar_active_bg(cx: &App) -> Hsla {
        cx.theme().list_active
    }
    /// Active toolbar item text → `sidebar_accent_foreground` (mockup
    /// `toolbarActiveText` = `fg`, `#cdd6f4`). The active nav icon is not
    /// white — the selection state is carried by the fill (`toolbar_active_bg`),
    /// not by the icon color (T037 §1.1.3).
    pub fn toolbar_active_text(cx: &App) -> Hsla {
        cx.theme().sidebar_accent_foreground
    }
    /// Toolbar border → `sidebar_border` (= `border`).
    pub fn toolbar_border(cx: &App) -> Hsla {
        cx.theme().sidebar_border
    }

    // --- Accent colors ------------------------------------------------------
    /// Primary accent (Chronos blue `007acc`) → `primary` (seed accent.primary).
    pub fn accent(cx: &App) -> Hsla {
        cx.theme().primary
    }
    /// Accent hover → `primary_hover`.
    pub fn accent_hover(cx: &App) -> Hsla {
        cx.theme().primary_hover
    }
    /// Light accent bg (subtle selection) → `selection`.
    pub fn accent_light(cx: &App) -> Hsla {
        cx.theme().selection
    }

    // --- Status -------------------------------------------------------------
    /// Danger / error → `danger` (seed status.error).
    pub fn danger(cx: &App) -> Hsla {
        cx.theme().danger
    }

    /// Muted color for disabled controls (mockup `disabled` token, `#45475a`).
    /// No dedicated `ThemeColor` field exists for this; call-site opacity on
    /// `muted_foreground` is the nearest match (T037 §1.1.2 — the theme JSON
    /// is deliberately left untouched).
    pub fn disabled(cx: &App) -> Hsla {
        let mut color = cx.theme().muted_foreground;
        color.a *= 0.7;
        color
    }
}
